name: Process Issues with Copilot
on:
  issues:
    types: [opened]

jobs:
  process_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run Copilot to process the issue
        run: |
          npx copilot-cli handle-issue --issue-number ${{ github.event.issue.number }}
